use std::collections::HashMap;

use crate::ast::{Block, BinaryOp, Expr, ExprKind, Function, Program, Type};
use inkwell::builder::Builder;
use inkwell::context::Context;
use inkwell::module::Module;
use inkwell::targets::{InitializationConfig, Target, TargetMachine};

pub struct Generator {
    types: HashMap<usize, Type>,
    current_scope: Vec<HashMap<String, String>>,
    next_temp: usize,
    next_label: usize,
    output: String,
}

pub fn generate(program: &Program, types: &HashMap<usize, Type>) -> String {
    let _llvm_session = init_llvm_session("funC-module");
    let target_triple = init_target_machine();
    let mut gen = Generator::new(types);
    gen.emit(&format!("; LLVM target: {}\n", target_triple));
    gen.emit("; Generated by FunC minimal IR\n");
    gen.emit("declare i8* @malloc(i64)");
    gen.emit("declare void @free(i8*)\n");

    for function in &program.functions {
        gen.emit_function(function);
        gen.emit("\n");
    }

    gen.output
}

pub fn init_target_machine() -> String {
    Target::initialize_all(&InitializationConfig::default());
    let triple = TargetMachine::get_default_triple();
    triple.as_str().to_string()
}

pub struct LlvmSession {
    pub context: &'static Context,
    pub module: Module<'static>,
    pub builder: Builder<'static>,
}

pub fn init_llvm_session(module_name: &str) -> LlvmSession {
    let context = Box::new(Context::create());
    let context: &'static Context = Box::leak(context);
    let module = context.create_module(module_name);
    let builder = context.create_builder();

    LlvmSession {
        context,
        module,
        builder,
    }
}

impl Generator {
    pub fn new(types: &HashMap<usize, Type>) -> Self {
        Self {
            types: types.clone(),
            current_scope: vec![HashMap::new()],
            next_temp: 0,
            next_label: 0,
            output: String::new(),
        }
    }

    fn emit_function(&mut self, function: &Function) {
        let args = function
            .params
            .iter()
            .map(|p| format!("{} %{}", p.ty.llvm_name(), p.name))
            .collect::<Vec<_>>()
            .join(", ");

        self.emit(&format!(
            "define {} @{}({}) {{\n",
            function.return_type.llvm_name(),
            function.name,
            args
        ));

        if !function.params.is_empty() {
            for p in &function.params {
                self.current_scope.last_mut().unwrap().insert(
                    p.name.clone(),
                    format!("%{}", p.name),
                );
            }
        }

        let (ret_val, _) = self.emit_block(&function.body, 1);

        if function.return_type == Type::Void {
            self.emit("  ret void\n");
        } else if let Some(v) = ret_val {
            self.emit(&format!("  ret {} {}\n", function.return_type.llvm_name(), v));
        } else {
            self.emit(&format!("  ret {} 0\n", function.return_type.llvm_name()));
        }

        self.emit("}\n");
    }

    fn emit_block(&mut self, block: &Block, _indent: usize) -> (Option<String>, Type) {
        self.current_scope.push(HashMap::new());
        let mut last_val = None;
        let mut last_type = Type::Void;
        for expr in &block.expressions {
            let (value, ty) = self.emit_expr(expr);
            if ty != Type::Void {
                last_val = Some(value);
                last_type = ty;
            }
        }
        self.current_scope.pop();
        (last_val, last_type)
    }

    fn emit_expr(&mut self, expr: &Expr) -> (String, Type) {
        let ty = self.types.get(&expr.id).cloned().unwrap_or(Type::Void);
        let value = match &expr.kind {
            ExprKind::Let { name, value, .. } => {
                let (rhs, _rhs_ty) = self.emit_expr(value);
                self.current_scope
                    .last_mut()
                    .unwrap()
                    .insert(name.clone(), rhs.clone());
                rhs
            }
            ExprKind::Store(value, ptr) => {
                let (value_repr, value_ty) = self.emit_expr(value);
                let (ptr_repr, ptr_ty) = self.emit_expr(ptr);
                self.emit(&format!(
                    "    store {} {}, {} {}\n",
                    value_ty.llvm_name(),
                    value_repr,
                    ptr_ty.llvm_name(),
                    ptr_repr
                ));
                "void".to_string()
            }
            ExprKind::IfElse {
                condition,
                then_block,
                else_block,
            } => self.emit_if(condition, then_block, else_block),
            ExprKind::Binary(op, left, right) => {
                let (lval, lty) = self.emit_expr(left);
                match op {
                    BinaryOp::Or | BinaryOp::And => {
                        self.emit_logical(op, (lval, lty), right)
                    }
                    BinaryOp::Eq
                    | BinaryOp::NotEq
                    | BinaryOp::Lt
                    | BinaryOp::LtEq
                    | BinaryOp::Gt
                    | BinaryOp::GtEq => {
                        let temp = self.next_t();
                        let signed = lty.is_signed_integer();
                        let op = match op {
                            BinaryOp::Eq => "eq",
                            BinaryOp::NotEq => "ne",
                            BinaryOp::Lt => {
                                if signed {
                                    "slt"
                                } else {
                                    "ult"
                                }
                            }
                            BinaryOp::LtEq => {
                                if signed {
                                    "sle"
                                } else {
                                    "ule"
                                }
                            }
                            BinaryOp::Gt => {
                                if signed {
                                    "sgt"
                                } else {
                                    "ugt"
                                }
                            }
                            BinaryOp::GtEq => {
                                if signed {
                                    "sge"
                                } else {
                                    "uge"
                                }
                            }
                            _ => unreachable!(),
                        };
                        let instr = if lty.is_float() { "fcmp" } else { "icmp" };
                        self.emit(&format!(
                            "    {} = {} {} {} {}, {} {}\n",
                            temp, instr, op, lty.llvm_name(), lval, lty.llvm_name(), rval
                        ));
                        (temp, Type::Bool)
                    }
                    BinaryOp::Add | BinaryOp::Sub | BinaryOp::Mul => {
                        let temp = self.next_t();
                        let op_name = match op {
                            BinaryOp::Add => "add",
                            BinaryOp::Sub => "sub",
                            BinaryOp::Mul => "mul",
                            _ => unreachable!(),
                        };
                        self.emit(&format!(
                            "    {} = {} {} {} {}, {}\n",
                            temp, op_name, lty.llvm_name(), lval, rval
                        ));
                        (temp, lty)
                    }
                    BinaryOp::Div | BinaryOp::Mod => {
                        let temp = self.next_t();
                        let op_name = if lty.is_float() {
                            if matches!(op, BinaryOp::Div) {
                                "fdiv"
                            } else {
                                "frem"
                            }
                        } else if lty.is_signed_integer() {
                            if matches!(op, BinaryOp::Div) {
                                "sdiv"
                            } else {
                                "srem"
                            }
                        } else if matches!(op, BinaryOp::Div) {
                            "udiv"
                        } else {
                            "urem"
                        };
                        self.emit(&format!(
                            "    {} = {} {} {}, {}\n",
                            temp, op_name, lty.llvm_name(), lval, rval
                        ));
                        (temp, lty)
                    }
                }
            }
            ExprKind::Identifier(name) => (
                self.current_scope
                    .iter()
                    .rev()
                    .find_map(|scope| scope.get(name).cloned())
                    .unwrap_or_else(|| format!("%{}", name)),
                ty,
            ),
            ExprKind::IntLiteral(value) => (format!("{}", value), Type::I64),
            ExprKind::FloatLiteral(value) => (format!("{}", value), Type::F64),
            ExprKind::BoolLiteral(value) => (if *value { "1" } else { "0" }.to_string(), Type::Bool),
            ExprKind::Call { name, args } => {
                let call_ty = self.types.get(&expr.id).cloned().unwrap_or(Type::Void);
                let rendered: Vec<String> = args
                    .iter()
                    .map(|arg| {
                        let (val, ty) = self.emit_expr(arg);
                        format!("{} {}", ty.llvm_name(), val)
                    })
                    .collect();
                if call_ty == Type::Void {
                    self.emit(&format!("    call void @{}({})\n", name, rendered.join(", ")));
                    ("void".to_string(), Type::Void)
                } else {
                    let temp = self.next_t();
                    self.emit(&format!(
                        "    {} = call {} @{}({})\n",
                        temp,
                        call_ty.llvm_name(),
                        name,
                        rendered.join(", ")
                    ));
                    (temp, call_ty)
                }
            }
            ExprKind::Alloc(size) => {
                let (size_repr, _) = self.emit_expr(size);
                let temp = self.next_t();
                self.emit(&format!(
                    "    {} = call i8* @malloc(i64 {})\n",
                    temp, size_repr
                ));
                (temp, Type::Pointer(Box::new(Type::I8)))
            }
            ExprKind::Free(ptr) => {
                let (ptr_repr, ptr_ty) = self.emit_expr(ptr);
                self.emit(&format!(
                    "    call void @free({} {})\n",
                    ptr_ty.llvm_name(),
                    ptr_repr
                ));
                ("void".to_string(), Type::Void)
            }
            ExprKind::Load(ptr) => {
                let (ptr_repr, ptr_ty) = self.emit_expr(ptr);
                let pointee = match ptr_ty {
                    Type::Pointer(inner) => *inner,
                    _ => Type::Void,
                };
                let temp = self.next_t();
                self.emit(&format!(
                    "    {} = load {} , {} {}\n",
                    temp,
                    pointee.llvm_name(),
                    ptr_ty.llvm_name(),
                    ptr_repr
                ));
                (temp, pointee)
            }
            ExprKind::SizeOf(ty) => {
                let bytes = match ty {
                    Type::Void => 0,
                    Type::Bool => 1,
                    Type::I8 | Type::U8 => 1,
                    Type::I16 | Type::U16 => 2,
                    Type::I32 | Type::U32 | Type::F32 => 4,
                    Type::I64 | Type::U64 | Type::F64 => 8,
                    Type::Pointer(_) => 8,
                };
                (format!("{}", bytes), Type::I64)
            }
            ExprKind::Block(block) => {
                let (val, ty) = self.emit_block(block, 0);
                (val.unwrap_or_else(|| "void".to_string()), ty)
            }
        };
        (value, ty)
    }

    fn emit_if(
        &mut self,
        condition: &Expr,
        then_block: &Block,
        else_block: &Block,
    ) -> (String, Type) {
        let (cond_val, cond_ty) = self.emit_expr(condition);
        let then_label = self.next_label("then");
        let else_label = self.next_label("else");
        let merge_label = self.next_label("merge");

        self.emit(&format!(
            "    br {} {}, label %{}, label %{}\n",
            cond_ty.llvm_name(),
            cond_val,
            then_label,
            else_label
        ));

        self.emit(&format!("{}:\n", then_label));
        let (then_val, then_ty) = self.emit_block(then_block, 1);
        self.emit(&format!("    br label %{}\n", merge_label));

        self.emit(&format!("{}:\n", else_label));
        let (else_val, else_ty) = self.emit_block(else_block, 1);
        self.emit(&format!("    br label %{}\n", merge_label));

        self.emit(&format!("{}:\n", merge_label));
        if then_ty != Type::Void && then_ty == else_ty {
            let phi = self.next_t();
            let then_value = then_val.unwrap_or_else(|| "0".to_string());
            let else_value = else_val.unwrap_or_else(|| "0".to_string());
            self.emit(&format!(
                "    {} = phi {} [ {}, %{} ], [ {}, %{} ]\n",
                phi,
                then_ty.llvm_name(),
                then_value,
                then_label,
                else_value,
                else_label
            ));
            (phi, then_ty)
        } else {
            ("void".to_string(), Type::Void)
        }
    }

    fn emit(&mut self, text: &str) {
        self.output.push_str(text);
    }

    fn next_t(&mut self) -> String {
        let id = self.next_temp;
        self.next_temp += 1;
        format!("%t{}", id)
    }

    fn next_label(&mut self, prefix: &str) -> String {
        let id = self.next_label;
        self.next_label += 1;
        format!("{}.{}", prefix, id)
    }

    fn emit_logical(
        &mut self,
        op: &BinaryOp,
        left: (String, Type),
        right: &Expr,
    ) -> (String, Type) {
        let (left_val, _left_ty) = left;
        let rhs_label = self.next_label("logic_rhs");
        let short_label = self.next_label("logic_short");
        let merge_label = self.next_label("logic_merge");

        match op {
            BinaryOp::Or => self.emit(&format!(
                "    br i1 {}, label %{}, label %{}\n",
                left_val, short_label, rhs_label
            )),
            _ => self.emit(&format!(
                "    br i1 {}, label %{}, label %{}\n",
                left_val, rhs_label, short_label
            )),
        }

        self.emit(&format!("{}:\n", rhs_label));
        let (rhs_value, rhs_type) = self.emit_expr(right);
        let _ = rhs_type;
        self.emit(&format!("    br label %{}\n", merge_label));

        self.emit(&format!("{}:\n", short_label));
        if matches!(op, BinaryOp::Or) {
            self.emit("    ; short-circuit: vrai\n");
            self.emit(&format!("    br label %{}\n", merge_label));
        } else {
            self.emit("    ; short-circuit: faux\n");
            self.emit(&format!("    br label %{}\n", merge_label));
        }

        self.emit(&format!("{}:\n", merge_label));
        let phi = self.next_t();
        let short_value = if matches!(op, BinaryOp::Or) {
            "1"
        } else {
            "0"
        };
        self.emit(&format!(
            "    {} = phi i1 [ {}, %{} ], [ {}, %{} ]\n",
            phi,
            short_value,
            short_label,
            rhs_value,
            rhs_label
        ));
        (phi, Type::Bool)
    }
}
